// import { LogginProvider } from "@/context/logginContext";
// import { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { getProducts } from "@/helpers/product.helper";
// import NavBar from "@/components/NavBar/NavBar";
// import Footer from "@/components/Footer/Footer";
// import ShowComponent from "@/components/ShowComponent/ShowComponent";
// import "./globals.css";
// import AsideList from "@/components/AsideList/AsideList";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "JhonDay Solutions",
//   description: "Generated by create next app",
// };

// async function getNavBarData() {
//   try {
//     const products = await getProducts();
//     return products.map((product) => ({
//       src: product.image,
//       link: `/product/${product.id}`,
//     }));
//   } catch (error) {
//     console.error("Error fetching products:", error);
//     return [];
//   }
// }

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const images = await getNavBarData();

//   return (
//     <html lang="en">
//       <body className={`${inter.className} flex flex-col h-screen w-full`}>
//         <LogginProvider>
//           <ShowComponent>
//             <NavBar images={images} />
//             <AsideList  />
//           </ShowComponent>
//           {children}
//           <Footer />
//         </LogginProvider>
//       </body>
//     </html>
//   );
// }


import { LogginProvider } from "@/context/logginContext";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { getProducts } from "@/helpers/product.helper";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import ShowComponent from "@/components/ShowComponent/ShowComponent";
import { GoogleOAuthProvider} from "@react-oauth/google";
import "./globals.css";
import AsideList from "@/components/AsideList/AsideList";
const inter = Inter({ subsets: ["latin"] });


const clientId = process.env.GOOGLE_CLIENT_ID || ""

console.log("ClientId:",process.env.GOOGLE_CLIENT_ID);

if (!clientId) {
  console.error("Google Client ID no está definido. Verifica tus variables de entorno.");
}


export const metadata: Metadata = {
  title: "Soluciones JhonDay",
  description: "Creative Commons",
};

async function getNavBarData() {
  try {
    const products = await getProducts();
    return products.map((product) => ({
      src: product.image,
      link: `/product/${product.id}`,
    }));
  } catch (error) {
    console.error("Error fetching products:", error);
    return [];
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const images = await getNavBarData();

  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen w-full`}>
        {/* GoogleOAuthProvider para la autenticación con Google */}
        <GoogleOAuthProvider clientId={clientId}>
          {/* AuthProvider para manejar la autenticación en el contexto */}
        <LogginProvider>
          <ShowComponent>
            <NavBar images={images} />
            <div className="flex flex-row justify-start">
              <div className="w-1/4">
                <AsideList />
              </div>
              <div className="flex-1 flex justify-center">
                {children}
              </div>
            </div>
          </ShowComponent>
          <Footer />
        </LogginProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}